### ISSUE TITLE
do we have x86_64 version gdb static ?

### ISSUE THREAD

**Issue by hezhiye** [imazes/gdb_static_for_all_arch#1]
Hi:
   thanks for your work.  It is really useful for me.
   But i need a x86_64  11.2 version gdb static .  I can not find arch for x86_64.

**Comment by imazes** [comment]
its will be provide later

**Comment by hezhiye** [comment]
ok, thanks.

**Comment by hezhiye** [comment]
sorry, by the way, when do you plan to provide this x86_64 arch gdb ?

**Comment by imazes** [comment]
gdb run err with static,but gdbserver work fine
