### ISSUE TITLE
有考虑提供armeb版本的gdbserver吗？

### ISSUE THREAD

**Issue by ioxv** [imazes/gdb_static_for_all_arch#2]
您好，非常感谢您能提供这么多版本的gdbserver。最近我在调试arm大端的设备，自己尝试使用armeb-none-eabi及armeb-linux-gnueabi（gcc-linaro）去生成be8的gdbserver，但是没有成功。请问您能提供一份armeb版本的gdb吗？或者提供一些编译思路，谢谢。

**Comment by imazes** [comment]
抱歉,armeb-gcc尚未被gnu官方支持,因此不再此队列
